# Generated by Django 4.2.6 on 2025-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_sliderimage_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
