# Generated by Django 4.2.6 on 2025-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="slider_images/"),
        ),
    ]
